### ISSUE TITLE
A small bug and question of eval  code

### ISSUE THREAD

**Issue by baibizhe** [lxtGH/OMG-Seg#27]
Thanks for this exciting work!
I am facing some problem when running the code. Would you mind help me with this?

![image](https://github.com/user-attachments/assets/21b3b946-3598-4981-bbf7-fdceadb9af39)

This should be gcg  instead of gcd?
I am having a hard time on  only eval on gcg_omg_seg_llava dataset . Would you mind help me with this?

My command is 
NPROC_PER_NODE=2 xtuner  gcg_omg_seg_llava   OMG-Seg/omg_llava/omg_llava/configs/finetune/specific_tasks_finetune/finetune_gcg.py  pretrained/omg_llava/  --output-name gcg_pred

Here are all files in  pretrained/omg_llava/   (basiclly , they are the files  at  https://huggingface.co/zhangtao-whu/OMG-LLaVA/tree/main)
![image](https://github.com/user-attachments/assets/a50776d5-f367-40b2-a80d-5d9d1227cb30).

After running the command above, it is shown this error:
```cmd
07/24 16:19:23 - mmengine - WARNING - Use random port: 25055
[2024-07-24 16:19:25,350] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
[2024-07-24 16:19:28,360] torch.distributed.run: [WARNING] 
[2024-07-24 16:19:28,360] torch.distributed.run: [WARNING] *****************************************
[2024-07-24 16:19:28,360] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-07-24 16:19:28,360] torch.distributed.run: [WARNING] *****************************************
[2024-07-24 16:19:31,502] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-24 16:19:31,502] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
/home/pai/envs/omg-llava/lib/python3.11/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/pai/envs/omg-llava/lib/python3.11/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:13<00:00,  1.75s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:13<00:00,  1.74s/it]
07/24 16:19:50 - mmengine - INFO - Loaded convnext_large_d_320 model config.
07/24 16:19:54 - mmengine - INFO - Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
Loadding CLIP from /root/.cache/huggingface/hub/models--laion--CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/snapshots/39918dfbdf69ccd2172e6510a430e92337ee23e1/open_clip_pytorch_model.bin !!!
dsw73375-8674f4bf9-r6fbz:227800:227800 [0] NCCL INFO Bootstrap : Using eth0:33.97.236.148<0>
dsw73375-8674f4bf9-r6fbz:227800:227800 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
dsw73375-8674f4bf9-r6fbz:227800:227800 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
dsw73375-8674f4bf9-r6fbz:227800:227800 [0] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.5+cuda11.8
dsw73375-8674f4bf9-r6fbz:227801:227801 [1] NCCL INFO cudaDriverVersion 12020
dsw73375-8674f4bf9-r6fbz:227801:227801 [1] NCCL INFO Bootstrap : Using eth0:33.97.236.148<0>
dsw73375-8674f4bf9-r6fbz:227801:227801 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
dsw73375-8674f4bf9-r6fbz:227801:227801 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB eth0:33.97.236.148<0>
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Using network IB
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB eth0:33.97.236.148<0>
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Using network IB
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO comm 0xfa16260 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 89000 commId 0x89112082a8fc5fc5 - Init START
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO comm 0x3c7a08e0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 8e000 commId 0x89112082a8fc5fc5 - Init START
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO NCCL_MAX_NCHANNELS set by environment to 2.
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO NCCL_MAX_NCHANNELS set by environment to 2.
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO NCCL_MIN_NCHANNELS set by environment to 2.
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO NCCL_MIN_NCHANNELS set by environment to 2.
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Channel 00/02 :    0   1
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Channel 01/02 :    0   1
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO P2P Chunksize set to 524288
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO P2P Chunksize set to 524288
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC/read
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/IPC/read
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC/read
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/IPC/read
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Connected all rings
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO Connected all trees
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Connected all rings
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO Connected all trees
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO NCCL_LAUNCH_MODE set by environment to PARALLEL
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO NCCL_LAUNCH_MODE set by environment to PARALLEL
dsw73375-8674f4bf9-r6fbz:227800:228181 [0] NCCL INFO comm 0xfa16260 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 89000 commId 0x89112082a8fc5fc5 - Init COMPLETE
dsw73375-8674f4bf9-r6fbz:227801:228182 [1] NCCL INFO comm 0x3c7a08e0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 8e000 commId 0x89112082a8fc5fc5 - Init COMPLETE
07/24 16:19:56 - mmengine - INFO - Loaded convnext_large_d_320 model config.
07/24 16:19:56 - mmengine - INFO - Loaded convnext_large_d_320 model config.
07/24 16:20:00 - mmengine - INFO - Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
Loadding CLIP from /root/.cache/huggingface/hub/models--laion--CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/snapshots/39918dfbdf69ccd2172e6510a430e92337ee23e1/open_clip_pytorch_model.bin !!!
07/24 16:20:00 - mmengine - INFO - Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
Loadding CLIP from /root/.cache/huggingface/hub/models--laion--CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/snapshots/39918dfbdf69ccd2172e6510a430e92337ee23e1/open_clip_pytorch_model.bin !!!
Loaded omg weight from ./pretrained/omg_llava/omg_seg_convl.pth !!!
07/24 16:20:01 - mmengine - INFO - replace InternLM2RotaryEmbedding
Loaded omg weight from ./pretrained/omg_llava/omg_seg_convl.pth !!!
07/24 16:20:01 - mmengine - INFO - replace InternLM2RotaryEmbedding
Frozen the Visual Encoder !
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
Frozen the Visual Encoder !
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
[SEG]: 92544, <p>: 92545, </p>: 92546, <region>: 92547, <mark>: 92548
****************************Add special tokens ********************************************
[SEG]: 92544, <p>: 92545, </p>: 92546, <region>: 92547, <mark>: 92548
****************************Add special tokens ********************************************
Unfrozen llm.base_model.model.model.tok_embeddings.weight !!!
Unfrozen llm.base_model.model.output.base_layer.weight !!!
Unfrozen llm.base_model.model.model.tok_embeddings.weight !!!
Unfrozen llm.base_model.model.output.base_layer.weight !!!
Load pretrained weight from ./pretrained/omg_llava/omg_llava_7b_finetune_8gpus.pth
Load pretrained weight from ./pretrained/omg_llava/omg_llava_7b_finetune_8gpus.pth
Init transformer_decoder_llm and resume omg seg decoder weight and not frozen !!!
Init mask_embed_llm and resume omg seg weight and not frozen !!!
Init transformer_decoder_llm and resume omg seg decoder weight and not frozen !!!
Init mask_embed_llm and resume omg seg weight and not frozen !!!
Processing zero checkpoint 'pretrained/omg_llava/'
Traceback (most recent call last):
  File "........OMG-Seg/omg_llava/omg_llava/tools/gcg_omg_seg_llava.py", line 484, in <module>
    main()
  File ".........OMG-Seg/omg_llava/omg_llava/tools/gcg_omg_seg_llava.py", line 210, in main
    state_dict = guess_load_checkpoint(args.pth_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..........OMG-Seg/omg_llava/xtuner/model/utils.py", line 335, in guess_load_checkpoint
    state_dict = get_fp32_state_dict_from_zero_checkpoint(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/omg-llava/lib/python3.11/site-packages/deepspeed/utils/zero_to_fp32.py", line 521, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir, exclude_frozen_parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/omg-llava/lib/python3.11/site-packages/deepspeed/utils/zero_to_fp32.py", line 204, in _get_fp32_state_dict_from_zero_checkpoint
    optim_files = get_optim_files(ds_checkpoint_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/omg-llava/lib/python3.11/site-packages/deepspeed/utils/zero_to_fp32.py", line 88, in get_optim_files
    return get_checkpoint_files(checkpoint_dir, "*_optim_states.pt")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/envs/omg-llava/lib/python3.11/site-packages/deepspeed/utils/zero_to_fp32.py", line 82, in get_checkpoint_files
    raise FileNotFoundError(f"can't find {glob_pattern} files in directory '{checkpoint_dir}'")
FileNotFoundError: can't find *_optim_states.pt files in directory 'pretrained/omg_llava/'
```
Seems that the optimizers's ckpt could not been found. How to solve this ? 
And since I only want to eval on this dataset, is there any ways to not load the optimizers ?

**Comment by zhang-tao-whu** [comment]
Hello, for the checkpoint, please provide the path to the pth model file, not the path to the parent folder.
You can retry this command:
```NPROC_PER_NODE=2 xtuner gcg_omg_seg_llava OMG-Seg/omg_llava/omg_llava/configs/finetune/specific_tasks_finetune/finetune_gcg.py pretrained/omg_llava/finetuned_gcg.pth --output-name gcg_pred```
